sudo: false
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libunbound-dev
    - libldns-dev
    - libidn11-dev
    - check
    - libevent-dev
    - libev-dev
    - bc
script:
  - libtoolize -fic
  - autoreconf -fi
  - mkdir tests
  - cd tests
  - ../src/test/tpkg/run-all.sh
